package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private Integer answerId;
     private byte[] answerDoc;
     private int questionQuestionId;
     private Date answerDateLastModified;
     private int authorAuthorId;

    public Answer() {
    }

    public Answer(byte[] answerDoc, int questionQuestionId, Date answerDateLastModified, int authorAuthorId) {
       this.answerDoc = answerDoc;
       this.questionQuestionId = questionQuestionId;
       this.answerDateLastModified = answerDateLastModified;
       this.authorAuthorId = authorAuthorId;
    }
   
    public Integer getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }
    public byte[] getAnswerDoc() {
        return this.answerDoc;
    }
    
    public void setAnswerDoc(byte[] answerDoc) {
        this.answerDoc = answerDoc;
    }
    public int getQuestionQuestionId() {
        return this.questionQuestionId;
    }
    
    public void setQuestionQuestionId(int questionQuestionId) {
        this.questionQuestionId = questionQuestionId;
    }
    public Date getAnswerDateLastModified() {
        return this.answerDateLastModified;
    }
    
    public void setAnswerDateLastModified(Date answerDateLastModified) {
        this.answerDateLastModified = answerDateLastModified;
    }
    public int getAuthorAuthorId() {
        return this.authorAuthorId;
    }
    
    public void setAuthorAuthorId(int authorAuthorId) {
        this.authorAuthorId = authorAuthorId;
    }




}


