package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Auditor generated by hbm2java
 */
public class Auditor  implements java.io.Serializable {


     private Integer auditorId;
     private Address address;
     private Contactdetail contactdetail;
     private Set auditses = new HashSet(0);

    public Auditor() {
    }

	
    public Auditor(Address address, Contactdetail contactdetail) {
        this.address = address;
        this.contactdetail = contactdetail;
    }
    public Auditor(Address address, Contactdetail contactdetail, Set auditses) {
       this.address = address;
       this.contactdetail = contactdetail;
       this.auditses = auditses;
    }
   
    public Integer getAuditorId() {
        return this.auditorId;
    }
    
    public void setAuditorId(Integer auditorId) {
        this.auditorId = auditorId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Contactdetail getContactdetail() {
        return this.contactdetail;
    }
    
    public void setContactdetail(Contactdetail contactdetail) {
        this.contactdetail = contactdetail;
    }
    public Set getAuditses() {
        return this.auditses;
    }
    
    public void setAuditses(Set auditses) {
        this.auditses = auditses;
    }




}


