package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private Integer authorId;
     private Address address;
     private Contactdetail contactdetail;
     private int informationInformationId;
     private Set instructions = new HashSet(0);

    public Author() {
    }

	
    public Author(Address address, Contactdetail contactdetail, int informationInformationId) {
        this.address = address;
        this.contactdetail = contactdetail;
        this.informationInformationId = informationInformationId;
    }
    public Author(Address address, Contactdetail contactdetail, int informationInformationId, Set instructions) {
       this.address = address;
       this.contactdetail = contactdetail;
       this.informationInformationId = informationInformationId;
       this.instructions = instructions;
    }
   
    public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Contactdetail getContactdetail() {
        return this.contactdetail;
    }
    
    public void setContactdetail(Contactdetail contactdetail) {
        this.contactdetail = contactdetail;
    }
    public int getInformationInformationId() {
        return this.informationInformationId;
    }
    
    public void setInformationInformationId(int informationInformationId) {
        this.informationInformationId = informationInformationId;
    }
    public Set getInstructions() {
        return this.instructions;
    }
    
    public void setInstructions(Set instructions) {
        this.instructions = instructions;
    }




}


