package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contactdetail generated by hbm2java
 */
public class Contactdetail  implements java.io.Serializable {


     private Integer contactDetailId;
     private String contactDetailCellNumber;
     private String contactDetailEmailAddress;
     private String contactDetailAlternativeMail;
     private String contactDetailAlternativeCellNumber;
     private Set employees = new HashSet(0);
     private Set authors = new HashSet(0);
     private Set auditors = new HashSet(0);

    public Contactdetail() {
    }

	
    public Contactdetail(String contactDetailCellNumber, String contactDetailEmailAddress) {
        this.contactDetailCellNumber = contactDetailCellNumber;
        this.contactDetailEmailAddress = contactDetailEmailAddress;
    }
    public Contactdetail(String contactDetailCellNumber, String contactDetailEmailAddress, String contactDetailAlternativeMail, String contactDetailAlternativeCellNumber, Set employees, Set authors, Set auditors) {
       this.contactDetailCellNumber = contactDetailCellNumber;
       this.contactDetailEmailAddress = contactDetailEmailAddress;
       this.contactDetailAlternativeMail = contactDetailAlternativeMail;
       this.contactDetailAlternativeCellNumber = contactDetailAlternativeCellNumber;
       this.employees = employees;
       this.authors = authors;
       this.auditors = auditors;
    }
   
    public Integer getContactDetailId() {
        return this.contactDetailId;
    }
    
    public void setContactDetailId(Integer contactDetailId) {
        this.contactDetailId = contactDetailId;
    }
    public String getContactDetailCellNumber() {
        return this.contactDetailCellNumber;
    }
    
    public void setContactDetailCellNumber(String contactDetailCellNumber) {
        this.contactDetailCellNumber = contactDetailCellNumber;
    }
    public String getContactDetailEmailAddress() {
        return this.contactDetailEmailAddress;
    }
    
    public void setContactDetailEmailAddress(String contactDetailEmailAddress) {
        this.contactDetailEmailAddress = contactDetailEmailAddress;
    }
    public String getContactDetailAlternativeMail() {
        return this.contactDetailAlternativeMail;
    }
    
    public void setContactDetailAlternativeMail(String contactDetailAlternativeMail) {
        this.contactDetailAlternativeMail = contactDetailAlternativeMail;
    }
    public String getContactDetailAlternativeCellNumber() {
        return this.contactDetailAlternativeCellNumber;
    }
    
    public void setContactDetailAlternativeCellNumber(String contactDetailAlternativeCellNumber) {
        this.contactDetailAlternativeCellNumber = contactDetailAlternativeCellNumber;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }
    public Set getAuditors() {
        return this.auditors;
    }
    
    public void setAuditors(Set auditors) {
        this.auditors = auditors;
    }




}


