package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private Address address;
     private Measurable measurable;
     private Set products = new HashSet(0);

    public Customer() {
    }

	
    public Customer(Address address, Measurable measurable) {
        this.address = address;
        this.measurable = measurable;
    }
    public Customer(Address address, Measurable measurable, Set products) {
       this.address = address;
       this.measurable = measurable;
       this.products = products;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Measurable getMeasurable() {
        return this.measurable;
    }
    
    public void setMeasurable(Measurable measurable) {
        this.measurable = measurable;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


