package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer employeeId;
     private Address address;
     private Contactdetail contactdetail;
     private Job job;
     private byte[] employeeContract;
     private byte[] employeeDocuments;
     private int informationInformationId;
     private Set managers = new HashSet(0);

    public Employee() {
    }

	
    public Employee(Address address, Contactdetail contactdetail, Job job, byte[] employeeContract, byte[] employeeDocuments, int informationInformationId) {
        this.address = address;
        this.contactdetail = contactdetail;
        this.job = job;
        this.employeeContract = employeeContract;
        this.employeeDocuments = employeeDocuments;
        this.informationInformationId = informationInformationId;
    }
    public Employee(Address address, Contactdetail contactdetail, Job job, byte[] employeeContract, byte[] employeeDocuments, int informationInformationId, Set managers) {
       this.address = address;
       this.contactdetail = contactdetail;
       this.job = job;
       this.employeeContract = employeeContract;
       this.employeeDocuments = employeeDocuments;
       this.informationInformationId = informationInformationId;
       this.managers = managers;
    }
   
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Contactdetail getContactdetail() {
        return this.contactdetail;
    }
    
    public void setContactdetail(Contactdetail contactdetail) {
        this.contactdetail = contactdetail;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public byte[] getEmployeeContract() {
        return this.employeeContract;
    }
    
    public void setEmployeeContract(byte[] employeeContract) {
        this.employeeContract = employeeContract;
    }
    public byte[] getEmployeeDocuments() {
        return this.employeeDocuments;
    }
    
    public void setEmployeeDocuments(byte[] employeeDocuments) {
        this.employeeDocuments = employeeDocuments;
    }
    public int getInformationInformationId() {
        return this.informationInformationId;
    }
    
    public void setInformationInformationId(int informationInformationId) {
        this.informationInformationId = informationInformationId;
    }
    public Set getManagers() {
        return this.managers;
    }
    
    public void setManagers(Set managers) {
        this.managers = managers;
    }




}


