package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1



/**
 * Goal generated by hbm2java
 */
public class Goal  implements java.io.Serializable {


     private Integer goalId;
     private Department department;
     private Process process;

    public Goal() {
    }

    public Goal(Department department, Process process) {
       this.department = department;
       this.process = process;
    }
   
    public Integer getGoalId() {
        return this.goalId;
    }
    
    public void setGoalId(Integer goalId) {
        this.goalId = goalId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }




}


