package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1



/**
 * Information generated by hbm2java
 */
public class Information  implements java.io.Serializable {


     private Integer informationId;
     private String informationName;
     private String informationSurname;
     private String informationIdNumber;

    public Information() {
    }

    public Information(String informationName, String informationSurname, String informationIdNumber) {
       this.informationName = informationName;
       this.informationSurname = informationSurname;
       this.informationIdNumber = informationIdNumber;
    }
   
    public Integer getInformationId() {
        return this.informationId;
    }
    
    public void setInformationId(Integer informationId) {
        this.informationId = informationId;
    }
    public String getInformationName() {
        return this.informationName;
    }
    
    public void setInformationName(String informationName) {
        this.informationName = informationName;
    }
    public String getInformationSurname() {
        return this.informationSurname;
    }
    
    public void setInformationSurname(String informationSurname) {
        this.informationSurname = informationSurname;
    }
    public String getInformationIdNumber() {
        return this.informationIdNumber;
    }
    
    public void setInformationIdNumber(String informationIdNumber) {
        this.informationIdNumber = informationIdNumber;
    }




}


