package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1



/**
 * Instruction generated by hbm2java
 */
public class Instruction  implements java.io.Serializable {


     private int instructionId;
     private Author author;
     private Process process;
     private String instructionOldNumber;
     private String instructionDescription;
     private String instructionArchivedPeriod;

    public Instruction() {
    }

	
    public Instruction(int instructionId, Author author, Process process) {
        this.instructionId = instructionId;
        this.author = author;
        this.process = process;
    }
    public Instruction(int instructionId, Author author, Process process, String instructionOldNumber, String instructionDescription, String instructionArchivedPeriod) {
       this.instructionId = instructionId;
       this.author = author;
       this.process = process;
       this.instructionOldNumber = instructionOldNumber;
       this.instructionDescription = instructionDescription;
       this.instructionArchivedPeriod = instructionArchivedPeriod;
    }
   
    public int getInstructionId() {
        return this.instructionId;
    }
    
    public void setInstructionId(int instructionId) {
        this.instructionId = instructionId;
    }
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }
    public String getInstructionOldNumber() {
        return this.instructionOldNumber;
    }
    
    public void setInstructionOldNumber(String instructionOldNumber) {
        this.instructionOldNumber = instructionOldNumber;
    }
    public String getInstructionDescription() {
        return this.instructionDescription;
    }
    
    public void setInstructionDescription(String instructionDescription) {
        this.instructionDescription = instructionDescription;
    }
    public String getInstructionArchivedPeriod() {
        return this.instructionArchivedPeriod;
    }
    
    public void setInstructionArchivedPeriod(String instructionArchivedPeriod) {
        this.instructionArchivedPeriod = instructionArchivedPeriod;
    }




}


