package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * IsoStandard generated by hbm2java
 */
public class IsoStandard  implements java.io.Serializable {


     private Integer isoStandardId;
     private String isoStandardName;
     private String isoStandardLink;
     private Set processes = new HashSet(0);

    public IsoStandard() {
    }

	
    public IsoStandard(String isoStandardName, String isoStandardLink) {
        this.isoStandardName = isoStandardName;
        this.isoStandardLink = isoStandardLink;
    }
    public IsoStandard(String isoStandardName, String isoStandardLink, Set processes) {
       this.isoStandardName = isoStandardName;
       this.isoStandardLink = isoStandardLink;
       this.processes = processes;
    }
   
    public Integer getIsoStandardId() {
        return this.isoStandardId;
    }
    
    public void setIsoStandardId(Integer isoStandardId) {
        this.isoStandardId = isoStandardId;
    }
    public String getIsoStandardName() {
        return this.isoStandardName;
    }
    
    public void setIsoStandardName(String isoStandardName) {
        this.isoStandardName = isoStandardName;
    }
    public String getIsoStandardLink() {
        return this.isoStandardLink;
    }
    
    public void setIsoStandardLink(String isoStandardLink) {
        this.isoStandardLink = isoStandardLink;
    }
    public Set getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Set processes) {
        this.processes = processes;
    }




}


