package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Measurable generated by hbm2java
 */
public class Measurable  implements java.io.Serializable {


     private Integer measurableId;
     private Process process;
     private String measurableDecription;
     private String measurableType;
     private Integer measurableOwner;
     private byte[] measurableDocuments;
     private Set customers = new HashSet(0);

    public Measurable() {
    }

	
    public Measurable(Process process, String measurableDecription, String measurableType) {
        this.process = process;
        this.measurableDecription = measurableDecription;
        this.measurableType = measurableType;
    }
    public Measurable(Process process, String measurableDecription, String measurableType, Integer measurableOwner, byte[] measurableDocuments, Set customers) {
       this.process = process;
       this.measurableDecription = measurableDecription;
       this.measurableType = measurableType;
       this.measurableOwner = measurableOwner;
       this.measurableDocuments = measurableDocuments;
       this.customers = customers;
    }
   
    public Integer getMeasurableId() {
        return this.measurableId;
    }
    
    public void setMeasurableId(Integer measurableId) {
        this.measurableId = measurableId;
    }
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }
    public String getMeasurableDecription() {
        return this.measurableDecription;
    }
    
    public void setMeasurableDecription(String measurableDecription) {
        this.measurableDecription = measurableDecription;
    }
    public String getMeasurableType() {
        return this.measurableType;
    }
    
    public void setMeasurableType(String measurableType) {
        this.measurableType = measurableType;
    }
    public Integer getMeasurableOwner() {
        return this.measurableOwner;
    }
    
    public void setMeasurableOwner(Integer measurableOwner) {
        this.measurableOwner = measurableOwner;
    }
    public byte[] getMeasurableDocuments() {
        return this.measurableDocuments;
    }
    
    public void setMeasurableDocuments(byte[] measurableDocuments) {
        this.measurableDocuments = measurableDocuments;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


