package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Period generated by hbm2java
 */
public class Period  implements java.io.Serializable {


     private Integer periodId;
     private Date periodStartDate;
     private Date periodEndDate;
     private double periodCompletionPercent;

    public Period() {
    }

    public Period(Date periodStartDate, Date periodEndDate, double periodCompletionPercent) {
       this.periodStartDate = periodStartDate;
       this.periodEndDate = periodEndDate;
       this.periodCompletionPercent = periodCompletionPercent;
    }
   
    public Integer getPeriodId() {
        return this.periodId;
    }
    
    public void setPeriodId(Integer periodId) {
        this.periodId = periodId;
    }
    public Date getPeriodStartDate() {
        return this.periodStartDate;
    }
    
    public void setPeriodStartDate(Date periodStartDate) {
        this.periodStartDate = periodStartDate;
    }
    public Date getPeriodEndDate() {
        return this.periodEndDate;
    }
    
    public void setPeriodEndDate(Date periodEndDate) {
        this.periodEndDate = periodEndDate;
    }
    public double getPeriodCompletionPercent() {
        return this.periodCompletionPercent;
    }
    
    public void setPeriodCompletionPercent(double periodCompletionPercent) {
        this.periodCompletionPercent = periodCompletionPercent;
    }




}


