package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Process generated by hbm2java
 */
public class Process  implements java.io.Serializable {


     private Integer processId;
     private IsoStandard isoStandard;
     private Processdata processdata;
     private int processRiskProcessRiskId;
     private String processType;
     private int periodPeriodId;
     private Set measurables = new HashSet(0);
     private Set instructions = new HashSet(0);
     private Set goals = new HashSet(0);
     private Processrisk processrisk;

    public Process() {
    }

	
    public Process(IsoStandard isoStandard, Processdata processdata, int processRiskProcessRiskId, String processType, int periodPeriodId) {
        this.isoStandard = isoStandard;
        this.processdata = processdata;
        this.processRiskProcessRiskId = processRiskProcessRiskId;
        this.processType = processType;
        this.periodPeriodId = periodPeriodId;
    }
    public Process(IsoStandard isoStandard, Processdata processdata, int processRiskProcessRiskId, String processType, int periodPeriodId, Set measurables, Set instructions, Set goals, Processrisk processrisk) {
       this.isoStandard = isoStandard;
       this.processdata = processdata;
       this.processRiskProcessRiskId = processRiskProcessRiskId;
       this.processType = processType;
       this.periodPeriodId = periodPeriodId;
       this.measurables = measurables;
       this.instructions = instructions;
       this.goals = goals;
       this.processrisk = processrisk;
    }
   
    public Integer getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }
    public IsoStandard getIsoStandard() {
        return this.isoStandard;
    }
    
    public void setIsoStandard(IsoStandard isoStandard) {
        this.isoStandard = isoStandard;
    }
    public Processdata getProcessdata() {
        return this.processdata;
    }
    
    public void setProcessdata(Processdata processdata) {
        this.processdata = processdata;
    }
    public int getProcessRiskProcessRiskId() {
        return this.processRiskProcessRiskId;
    }
    
    public void setProcessRiskProcessRiskId(int processRiskProcessRiskId) {
        this.processRiskProcessRiskId = processRiskProcessRiskId;
    }
    public String getProcessType() {
        return this.processType;
    }
    
    public void setProcessType(String processType) {
        this.processType = processType;
    }
    public int getPeriodPeriodId() {
        return this.periodPeriodId;
    }
    
    public void setPeriodPeriodId(int periodPeriodId) {
        this.periodPeriodId = periodPeriodId;
    }
    public Set getMeasurables() {
        return this.measurables;
    }
    
    public void setMeasurables(Set measurables) {
        this.measurables = measurables;
    }
    public Set getInstructions() {
        return this.instructions;
    }
    
    public void setInstructions(Set instructions) {
        this.instructions = instructions;
    }
    public Set getGoals() {
        return this.goals;
    }
    
    public void setGoals(Set goals) {
        this.goals = goals;
    }
    public Processrisk getProcessrisk() {
        return this.processrisk;
    }
    
    public void setProcessrisk(Processrisk processrisk) {
        this.processrisk = processrisk;
    }




}


