package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Processrisk generated by hbm2java
 */
public class Processrisk  implements java.io.Serializable {


     private Integer processRiskId;
     private Process process;
     private String processRiskDescription;
     private String processRiskType;
     private String processRiskResponse;
     private Date processRiskDueDate;
     private Date processRiskClosedDate;
     private String processRiskCurrentControls;

    public Processrisk() {
    }

	
    public Processrisk(Process process, String processRiskDescription, String processRiskType, String processRiskResponse) {
        this.process = process;
        this.processRiskDescription = processRiskDescription;
        this.processRiskType = processRiskType;
        this.processRiskResponse = processRiskResponse;
    }
    public Processrisk(Process process, String processRiskDescription, String processRiskType, String processRiskResponse, Date processRiskDueDate, Date processRiskClosedDate, String processRiskCurrentControls) {
       this.process = process;
       this.processRiskDescription = processRiskDescription;
       this.processRiskType = processRiskType;
       this.processRiskResponse = processRiskResponse;
       this.processRiskDueDate = processRiskDueDate;
       this.processRiskClosedDate = processRiskClosedDate;
       this.processRiskCurrentControls = processRiskCurrentControls;
    }
   
    public Integer getProcessRiskId() {
        return this.processRiskId;
    }
    
    public void setProcessRiskId(Integer processRiskId) {
        this.processRiskId = processRiskId;
    }
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }
    public String getProcessRiskDescription() {
        return this.processRiskDescription;
    }
    
    public void setProcessRiskDescription(String processRiskDescription) {
        this.processRiskDescription = processRiskDescription;
    }
    public String getProcessRiskType() {
        return this.processRiskType;
    }
    
    public void setProcessRiskType(String processRiskType) {
        this.processRiskType = processRiskType;
    }
    public String getProcessRiskResponse() {
        return this.processRiskResponse;
    }
    
    public void setProcessRiskResponse(String processRiskResponse) {
        this.processRiskResponse = processRiskResponse;
    }
    public Date getProcessRiskDueDate() {
        return this.processRiskDueDate;
    }
    
    public void setProcessRiskDueDate(Date processRiskDueDate) {
        this.processRiskDueDate = processRiskDueDate;
    }
    public Date getProcessRiskClosedDate() {
        return this.processRiskClosedDate;
    }
    
    public void setProcessRiskClosedDate(Date processRiskClosedDate) {
        this.processRiskClosedDate = processRiskClosedDate;
    }
    public String getProcessRiskCurrentControls() {
        return this.processRiskCurrentControls;
    }
    
    public void setProcessRiskCurrentControls(String processRiskCurrentControls) {
        this.processRiskCurrentControls = processRiskCurrentControls;
    }




}


