package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Processdata generated by hbm2java
 */
public class Processdata  implements java.io.Serializable {


     private Integer processDataId;
     private Record record;
     private String processDataDescription;
     private String processDataReviewFrequency;
     private String processDataArchivePeriod;
     private Integer processDataAuth;
     private byte[] processDataDocument;
     private Set processes = new HashSet(0);

    public Processdata() {
    }

	
    public Processdata(Record record) {
        this.record = record;
    }
    public Processdata(Record record, String processDataDescription, String processDataReviewFrequency, String processDataArchivePeriod, Integer processDataAuth, byte[] processDataDocument, Set processes) {
       this.record = record;
       this.processDataDescription = processDataDescription;
       this.processDataReviewFrequency = processDataReviewFrequency;
       this.processDataArchivePeriod = processDataArchivePeriod;
       this.processDataAuth = processDataAuth;
       this.processDataDocument = processDataDocument;
       this.processes = processes;
    }
   
    public Integer getProcessDataId() {
        return this.processDataId;
    }
    
    public void setProcessDataId(Integer processDataId) {
        this.processDataId = processDataId;
    }
    public Record getRecord() {
        return this.record;
    }
    
    public void setRecord(Record record) {
        this.record = record;
    }
    public String getProcessDataDescription() {
        return this.processDataDescription;
    }
    
    public void setProcessDataDescription(String processDataDescription) {
        this.processDataDescription = processDataDescription;
    }
    public String getProcessDataReviewFrequency() {
        return this.processDataReviewFrequency;
    }
    
    public void setProcessDataReviewFrequency(String processDataReviewFrequency) {
        this.processDataReviewFrequency = processDataReviewFrequency;
    }
    public String getProcessDataArchivePeriod() {
        return this.processDataArchivePeriod;
    }
    
    public void setProcessDataArchivePeriod(String processDataArchivePeriod) {
        this.processDataArchivePeriod = processDataArchivePeriod;
    }
    public Integer getProcessDataAuth() {
        return this.processDataAuth;
    }
    
    public void setProcessDataAuth(Integer processDataAuth) {
        this.processDataAuth = processDataAuth;
    }
    public byte[] getProcessDataDocument() {
        return this.processDataDocument;
    }
    
    public void setProcessDataDocument(byte[] processDataDocument) {
        this.processDataDocument = processDataDocument;
    }
    public Set getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Set processes) {
        this.processes = processes;
    }




}


