package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1



/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer questionId;
     private String questionData;
     private int tabTabId;

    public Question() {
    }

    public Question(String questionData, int tabTabId) {
       this.questionData = questionData;
       this.tabTabId = tabTabId;
    }
   
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public String getQuestionData() {
        return this.questionData;
    }
    
    public void setQuestionData(String questionData) {
        this.questionData = questionData;
    }
    public int getTabTabId() {
        return this.tabTabId;
    }
    
    public void setTabTabId(int tabTabId) {
        this.tabTabId = tabTabId;
    }




}


