package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Record generated by hbm2java
 */
public class Record  implements java.io.Serializable {


     private Integer recordId;
     private String recordDescription;
     private byte[] recordDocuments;
     private String recordArchivedPeriod;
     private Set processdatas = new HashSet(0);

    public Record() {
    }

    public Record(String recordDescription, byte[] recordDocuments, String recordArchivedPeriod, Set processdatas) {
       this.recordDescription = recordDescription;
       this.recordDocuments = recordDocuments;
       this.recordArchivedPeriod = recordArchivedPeriod;
       this.processdatas = processdatas;
    }
   
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }
    public String getRecordDescription() {
        return this.recordDescription;
    }
    
    public void setRecordDescription(String recordDescription) {
        this.recordDescription = recordDescription;
    }
    public byte[] getRecordDocuments() {
        return this.recordDocuments;
    }
    
    public void setRecordDocuments(byte[] recordDocuments) {
        this.recordDocuments = recordDocuments;
    }
    public String getRecordArchivedPeriod() {
        return this.recordArchivedPeriod;
    }
    
    public void setRecordArchivedPeriod(String recordArchivedPeriod) {
        this.recordArchivedPeriod = recordArchivedPeriod;
    }
    public Set getProcessdatas() {
        return this.processdatas;
    }
    
    public void setProcessdatas(Set processdatas) {
        this.processdatas = processdatas;
    }




}


