package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer supplierId;
     private Audits audits;

    public Supplier() {
    }

    public Supplier(Audits audits) {
       this.audits = audits;
    }
   
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public Audits getAudits() {
        return this.audits;
    }
    
    public void setAudits(Audits audits) {
        this.audits = audits;
    }




}


