package Model;
// Generated Mar 15, 2016 8:50:47 AM by Hibernate Tools 4.3.1



/**
 * Tab generated by hbm2java
 */
public class Tab  implements java.io.Serializable {


     private Integer tabId;
     private String tabTitle;
     private int isoStandardIsoStandardId;

    public Tab() {
    }

    public Tab(String tabTitle, int isoStandardIsoStandardId) {
       this.tabTitle = tabTitle;
       this.isoStandardIsoStandardId = isoStandardIsoStandardId;
    }
   
    public Integer getTabId() {
        return this.tabId;
    }
    
    public void setTabId(Integer tabId) {
        this.tabId = tabId;
    }
    public String getTabTitle() {
        return this.tabTitle;
    }
    
    public void setTabTitle(String tabTitle) {
        this.tabTitle = tabTitle;
    }
    public int getIsoStandardIsoStandardId() {
        return this.isoStandardIsoStandardId;
    }
    
    public void setIsoStandardIsoStandardId(int isoStandardIsoStandardId) {
        this.isoStandardIsoStandardId = isoStandardIsoStandardId;
    }




}


